# Generated by Django 4.2.2 on 2023-07-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_disciplina_pessoa_delete_banda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ano_letivo',
            field=models.CharField(max_length=20),
        ),
    ]
