# Generated by Django 4.2.2 on 2023-06-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_autor_delete_author_delete_cadeira_delete_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criador', models.CharField(max_length=100)),
                ('linguagens_usadas', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ano_realizacao', models.PositiveIntegerField()),
                ('link_github', models.URLField()),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.disciplina')),
                ('competencias', models.ManyToManyField(to='portfolio.competencia')),
                ('tecnologias_usadas', models.ManyToManyField(to='portfolio.lingua')),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='coment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.DeleteModel(
            name='Coment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
