# Generated by Django 4.2.2 on 2023-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_disciplina_professores_disciplina_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='topicos_abordados',
            field=models.CharField(max_length=300),
        ),
    ]
