# Generated by Django 4.2.2 on 2023-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_disciplina_topicos_abordados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('prioridade', models.IntegerField(default=1)),
                ('concluida', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
