# Generated by Django 4.2.2 on 2023-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professores',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ficheiro',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/blogueira'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/blogueira'),
        ),
    ]
