# Generated by Django 4.2.2 on 2023-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
