# Generated by Django 4.2.2 on 2023-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_post_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ficheiro',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/static/portfolio/images'),
        ),
    ]
