# Generated by Django 4.2.2 on 2023-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_post_likes_alter_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
